### ISSUE TITLE
Only first import highlighted

### ISSUE THREAD

**Issue by liam0215** [harmonylang/harmonylang#34]
It appears as if syntax highlighting only works for the first import statement.

![image](https://user-images.githubusercontent.com/8989334/114483120-d17e8080-9bd5-11eb-874e-13a32de42c5d.png)
![image](https://user-images.githubusercontent.com/8989334/114483179-eeb34f00-9bd5-11eb-9ac2-2c5f499eebd0.png)

**Comment by kevinsun-dev** [comment]
Issue appears to be fixed in PR #30 and is no longer an issue in the current release.
<img width="567" alt="Screen Shot 2022-01-31 at 11 02 12 AM" src="https://user-images.githubusercontent.com/12884206/151828478-0279651d-244d-4cda-87bd-d595e2979d14.png">
